version: '3'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server

  mlflow-server:
    image: mlflow/mlflow:latest
    container_name: mlflow-server
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns