services:
  app:
    build: .
    volumes:
      - .:/app  # Mount the current local directory to /app in the container
    ports:
      - "8001:8000"  # Flask port mapping
      - "6001:6000"  # MLflow server port mapping
    environment:
      - FLASK_ENV=dev
    develop:
      watch:
        - action: rebuild
          path: .